### ISSUE TITLE
Trying to relocate GStreamer framework, some libraries won't be relocated by install_name_tool

### ISSUE THREAD

**Issue by arvindnrbt** [tito/osxrelocator#2]
**command**: osxrelocator ./GStreamer-devel.framework/Versions/Current /Library/Frameworks/GStreamer.framework/ `pwd`/GStreamer-devel.framework/
--
ccall ['otool', '-L', './GStreamer-devel.framework/Versions/Current/GStreamer']
call ['install_name_tool', '-change', '/Library/Frameworks/GStreamer.framework/Versions/1.0/lib/GStreamer', '/Users/../../../../GStreamer-devel.framework/Versions/1.0/lib/GStreamer', './GStreamer-devel.framework/Versions/Current/GStreamer']
call ['install_name_tool', '-change', '/Library/Frameworks/GStreamer.framework/Versions/1.0/lib/libgstgl-1.0.0.dylib', '/Users/../../../../GStreamer-devel.framework/Versions/1.0/lib/libgstgl-1.0.0.dylib', './GStreamer-devel.framework/Versions/Current/GStreamer']

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: changing install names or rpaths can't be redone for: ./GStreamer-devel.framework/Versions/Current/GStreamer (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)

**Traceback (most recent call last):**
  File "/usr/local/bin/osxrelocator", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/osxrelocator/__init__.py", line 157, in main
    main.run()
  File "/Library/Python/2.7/site-packages/osxrelocator/__init__.py", line 152, in run
    relocator.relocate()
  File "/Library/Python/2.7/site-packages/osxrelocator/__init__.py", line 70, in relocate
    self.parse_dir(self.root, filters=['', '.dylib', '.so'])
  File "/Library/Python/2.7/site-packages/osxrelocator/__init__.py", line 102, in parse_dir
    self.relocate_file(fn)
  File "/Library/Python/2.7/site-packages/osxrelocator/__init__.py", line 73, in relocate_file
    self.change_libs_path(object_file)
  File "/Library/Python/2.7/site-packages/osxrelocator/__init__.py", line 89, in change_libs_path
    shell_call(cmd)
  File "/Library/Python/2.7/site-packages/osxrelocator/__init__.py", line 36, in shell_call
    raise SystemError("Error running command: {}".format(cmd))

**SystemError**: Error running command: ['install_name_tool', '-change', '/Library/Frameworks/GStreamer.framework/Versions/1.0/lib/libgstgl-1.0.0.dylib', '/Users/../../../../GStreamer-devel.framework/Versions/1.0/lib/libgstgl-1.0.0.dylib', './GStreamer-devel.framework/Versions/Current/GStreamer']

**Comment by eitzenbe** [comment]
Also affected by this, problem seems to be related to the pkged libs....
